sudo: false
language: cpp
matrix:
  include:
    - os: osx
      compiler: gcc

    - os: osx
      compiler: clang

    - os: linux
      compiler: gcc
      env: NOCHECK=1

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.8']
      env: COMPILER=g++-4.8

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9']
      env: COMPILER=g++-4.9

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env: COMPILER=g++-5

    - os: linux
      compiler: clang

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.5']
          packages: ['clang-3.5']
      env: COMPILER=clang++-3.5

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6']
          packages: ['clang-3.6']
      env: COMPILER=clang++-3.6

# Activate when 3.7 is released and the repository is available
#    - os: linux
#      compiler: clang
#      addons:
#        apt:
#          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
#          packages: ['clang-3.7']
#      env: COMPILER=clang++-3.7

script:
  - if [ x"$COMPILER" != "x" ]; then
      export CXX=$COMPILER;
    fi
  - mkdir -p m4
  - autoreconf --install
  - ./configure
  - make -j;
  - if [ x"$NOCHECK" == "x" ]; then
      git clone https://github.com/joakimkarlsson/igloo.git;
      cd igloo;
      git checkout igloo.1.1.1;
      cd ..;
      make check -j;
    fi
