sudo: false
script:
  - mkdir -p m4
  - autoreconf --install
  - ./configure
  - make
  - git clone https://github.com/joakimkarlsson/igloo.git
  - cd igloo
  - git checkout igloo.1.1.1
  - cd ..
  - make check
language: cpp
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
