#sudo: false
language: cpp
matrix:
  include:
    - os: osx
      compiler: gcc

    - os: osx
      compiler: clang

    - os: linux
      compiler: gcc
      env: NOCHECK=1

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.8']
      env: COMPILER=g++-4.8 GCOV=gcov-4.8

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9']
      env: COMPILER=g++-4.9 GCOV=gcov-4.9

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env: COMPILER=g++-5 GCOV=gcov-5

    - os: linux
      compiler: clang

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.5']
          packages: ['clang-3.5']
      env: COMPILER=clang++-3.5

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6']
          packages: ['clang-3.6']
      env: COMPILER=clang++-3.6

# Activate when 3.7 is released and the repository is available
#    - os: linux
#      compiler: clang
#      addons:
#        apt:
#          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
#          packages: ['clang-3.7']
#      env: COMPILER=clang++-3.7

install:
  - cd ${TRAVIS_BUILD_DIR}
  - if [ x"$COMPILER" != "x" ]; then
      export CXX=$COMPILER;
    fi
  - if [ x"$GCOV" != "x" ]; then
      sudo ln -sf /usr/bin/$GCOV /usr/bin/gcov;
    fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz;
      tar xf lcov_1.11.orig.tar.gz;
      sudo make -C lcov-1.11/ install;
      gem install coveralls-lcov;
    fi

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - if [ x"$COMPILER" != "x" ]; then
      export CXX=$COMPILER;
    fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      lcov --directory . --zerocounters;
    fi

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - if [ x"$COMPILER" != "x" ]; then
      export CXX=$COMPILER;
    fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      lcov --directory . --capture --output-file coverage.info;
      lcov --remove coverage.info 'tests/*' '/usr/*' 'igloo/*' --output-file coverage.info;
      lcov --list coverage.info;
      coveralls-lcov --repo-token 9lWbvZ16FTBPoyD2ackR7ssTwgUb740Jk coverage.info;
    fi

script:
  - cd ${TRAVIS_BUILD_DIR}
  - if [ x"$COMPILER" != "x" ]; then
      export CXX=$COMPILER;
    fi
  - mkdir -p m4
  - autoreconf --install
  - if [ x"$GCOV" == "x" ]; then
      ./configure;
    else
      ./configure CXXFLAGS="--coverage" --enable-coveralls;
    fi
  - make -j;
  - if [ x"$NOCHECK" == "x" ]; then
      git clone https://github.com/joakimkarlsson/igloo.git;
      cd igloo;
      git checkout igloo.1.1.1;
      cd ..;
      make check -j;
    fi
