sudo: required
language: cpp
matrix:
  include:
    - os: linux
      compiler: gcc
      env:
        - secure: "pmx0XqezDiYWojAB1cskaFa30uBnhaQDVU/L6oBz69V5Hff8vIqeobUpRSwWvp/MZLfNExGLNI/bQ5kzU8QhH0U8EpqCYeWqtDJTX/4wusyosVgFIrW1K39+v53WCcWowKnWxzt1uDtdwttygq6Y2n+JRW0fM9h+kZfLnWmSkdfC/3drchAg0mtiIWxLYdhIEWb/adtjcgFKimDFxsX4sG2ejSsEfMvJ6np3QPMlpgbVR9bjt6q7E4RpnHZRweVRsxCjsZN/lx4pYuF8gYTs/+vS3L7qMF+FfZR7SdOtvCNCx9PxQ+c2bnep21YsZceqApqtlJVz6NKM2aFP7EgfPBROkBEG6LyYymNk79dPszTesNZP2SQs4jXUpC3a9pRci48fwPLTmDa81SSDEeaDcfgrDWR9ZZiAi/NQN4w16XGK29t+qNEH1GI8vAoVE0UpAn9Maa3UxqZY+yAQoRux0FaVHsY3So+XNcGWBRhjdFSZWdoHJ9Uzr+LfQCoTAg8NaUzGS6W/xAbz86+HOu2QdeA94RYjycNUjd4goUIcIxx9gOaXh/GJCYO1OAI2svRqRnI3l5GlLJW+yH7shvFbqauxKrw/ODXEjuq13E6z+YB+RfYRsSXNrigd/7yNmRELOhgqnk0hNGRLvYIFqgJMn7YdGztbAfxYVkmCLGqWmDE="
      addons:
        coverity_scan:
          project:
            name: "mkrufky/valueobj"
            description: "Build submitted via Travis CI"
          notification_email: mkrufky@linuxtv.org
          build_command_prepend: "mkdir -p m4; autoreconf --install; ./configure; make clean"
          build_command:   "make -j"
          branch_pattern: coverity
      env: NOCHECK=1

    - os: osx
      compiler: gcc

    - os: osx
      compiler: clang

# Disabled to avoid duplication with the coverity scan version
#    - os: linux
#      compiler: gcc
#      env: NOCHECK=1

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.8']
      env: COMPILER=g++-4.8 GCOV=gcov-4.8

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9']
      env: COMPILER=g++-4.9 GCOV=gcov-4.9

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env: COMPILER=g++-5 GCOV=gcov-5

    - os: linux
      compiler: clang

# temporarily disabled due to error:
# `The command "curl -sSL "http://llvm.org/apt/llvm-snapshot.gpg.key" | sudo -E apt-key add -" failed and exited with 2 during .`
#
#    - os: linux
#      compiler: clang
#      addons:
#        apt:
#          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.5']
#          packages: ['clang-3.5']
#      env: COMPILER=clang++-3.5

#    - os: linux
#      compiler: clang
#      addons:
#        apt:
#          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6']
#          packages: ['clang-3.6']
#      env: COMPILER=clang++-3.6

# Activate when 3.7 is released and the repository is available
#    - os: linux
#      compiler: clang
#      addons:
#        apt:
#          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
#          packages: ['clang-3.7']
#      env: COMPILER=clang++-3.7

install:
  - cd ${TRAVIS_BUILD_DIR}
  - if [ x"$COMPILER" != "x" ]; then
      export CXX=$COMPILER;
    fi
  - if [ x"$GCOV" != "x" ]; then
      sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/$GCOV 90;
    fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz;
      tar xf lcov_1.11.orig.tar.gz;
      sudo make -C lcov-1.11/ install;
      gem install coveralls-lcov;
    fi

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - if [ x"$COMPILER" != "x" ]; then
      export CXX=$COMPILER;
    fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      lcov --directory . --zerocounters;
    fi

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - if [ x"$COMPILER" != "x" ]; then
      export CXX=$COMPILER;
    fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      lcov --directory . --capture --output-file coverage.info;
      lcov --remove coverage.info 'tests/*' '/usr/*' 'igloo/*' --output-file coverage.info;
      lcov --list coverage.info;
      coveralls-lcov --repo-token 9lWbvZ16FTBPoyD2ackR7ssTwgUb740Jk coverage.info;
    fi

script:
  - cd ${TRAVIS_BUILD_DIR}
  - if [ x"$COMPILER" != "x" ]; then
      export CXX=$COMPILER;
    fi
  - mkdir -p m4
  - autoreconf --install
  - if [ x"$GCOV" == "x" ]; then
      ./configure;
    else
      ./configure CXXFLAGS="--coverage" --enable-coveralls;
    fi
  - make -j;
  - if [ x"$NOCHECK" == "x" ]; then
      git clone https://github.com/joakimkarlsson/igloo.git;
      cd igloo;
      git checkout igloo.1.1.1;
      cd ..;
      make check -j;
    fi
