os: unstable
install:
  - set QTDIR=C:\Qt\5.4\mingw491_32
  - set PATH=%QTDIR%\bin;C:\MinGW\bin;%PATH%
build_script:
  - cd src
  - qmake value.pro
  - mingw32-make
  - cd ..
  - git clone -q https://github.com/joakimkarlsson/igloo.git
  - cd igloo
  - git checkout igloo.1.1.1
  - cd ..
  - cd tests
  - qmake tests.pro
  - mingw32-make -j
  - mingw32-make check
